add apache_server_status_listen_port var
rhythmictech/ansible-role-apache pull request #4
Opened 2022-04-27 16:50 UTC by sblack4

2022-04-27 16:52 UTC, jjduverge approved these changes

2022-12-06 01:41 UTC, sdickenson requested changes
I'm inclined to close this PR because I'm not sure the point of it. The changes to the server-status setup are not functional for our usage of this role. We could parameterize them but it doesn't ring true to how we use this role elsewhere. Generally if we needed to extend Apache with an additional listener and/or VirtualHost, we'd use another role or task to drop in a file to `/etc/httpd/conf.d` that does what we want. That would be a better approach in my opinion.

2022-12-06 01:41 UTC, sdickenson commented on templates/etc.httpd.conf.httpd.conf.j2
> +Listen                  {{ apache_server_status_listen_port }}
You can't do this. If you have overlapping Listen directives, Apache will fail to start.

2022-12-06 01:41 UTC, sdickenson commented on templates/etc.httpd.conf.httpd.conf.j2
> +<VirtualHost *:{{ apache_server_status_listen_port }}>
This would need to be parameterized since you can't have overlapping VirtualHosts on the same port without a distinct ServerName directive.

2022-12-06 13:08 UTC, cdaniluk commented
Are we using this anywhere by commit hash? It's weird that it was written in April and sat this long unapproved.

2022-12-06 15:28 UTC, sblack4 commented
We can close this - it was to let us host a site on a different port than the health check. We ended up fixing it here https://github.com/rhythmictech/ansible-role-nexus3/commit/7358f5e3cd770198ee8daeb1aed2179cd7e924e0

2022-12-06 15:28 UTC, closed without merging